apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp
  labels:
    app: scaletestapp
spec:
  selector:
    matchLabels:
      app: scaletestapp
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
        - name: scaletestapp
          image: shestera/scaletestapp
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 10Mi